  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQYQujWWp1rvfF2xmF-Rhd0eJoh_qWyE',
    appId: '1:273842681931:web:26db0952a39f71aeccb5ce',
    messagingSenderId: '273842681931',
    projectId: 'my-ecommerce-app-123-e47a9',
    authDomain: 'my-ecommerce-app-123-e47a9.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-e47a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1j4Fn_Dy9pvSk1jJVpFYDfYmdfYOFz-4',
    appId: '1:273842681931:android:0b896944585bab85ccb5ce',
    messagingSenderId: '273842681931',
    projectId: 'my-ecommerce-app-123-e47a9',
    storageBucket: 'my-ecommerce-app-123-e47a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB74Ml6ifd62jIQR0Zdgv8LfLMoqJWsgRM',
    appId: '1:273842681931:ios:7209bc8d3ab24f4bccb5ce',
    messagingSenderId: '273842681931',
    projectId: 'my-ecommerce-app-123-e47a9',
    storageBucket: 'my-ecommerce-app-123-e47a9.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB74Ml6ifd62jIQR0Zdgv8LfLMoqJWsgRM',
    appId: '1:273842681931:ios:7209bc8d3ab24f4bccb5ce',
    messagingSenderId: '273842681931',
    projectId: 'my-ecommerce-app-123-e47a9',
    storageBucket: 'my-ecommerce-app-123-e47a9.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVQYQujWWp1rvfF2xmF-Rhd0eJoh_qWyE',
    appId: '1:273842681931:web:4e642608adcfe99cccb5ce',
    messagingSenderId: '273842681931',
    projectId: 'my-ecommerce-app-123-e47a9',
    authDomain: 'my-ecommerce-app-123-e47a9.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-e47a9.firebasestorage.app',
  );
}
